name: Fast APK Generator
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build APK (Auto-Answers)
        run: |
          npm install -g @bubblewrap/cli
          # هاد الأمر كينشأ الإعدادات أولا بلا ما يسولك
          bubblewrap init --manifest=https://chrsd-ca487.web.app/manifest.json --directory=./ --metaData.noStatusUpdate
          
          # هاد السطر السحري كيجاوب "Yes" على كاع الأسئلة (JDK, Android SDK, etc.)
          printf "y\ny\ny\ny\ny\ny\n" | bubblewrap build --skipPasswordPrompt
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-App-APK
          path: ./*.apk
