name: Build APK Fast
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build APK
        run: |
          npm install -g @bubblewrap/cli
          # هاد السطر كيجاوب "نعم" على كاع أسئلة الإعداد أوتوماتيكياً
          yes | bubblewrap init --manifest=https://chrsd-ca487.web.app/manifest.json
          yes | bubblewrap build --skipPasswordPrompt
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-pwa-apk
          path: ./*.apk
