name: Build APK Final
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Android App (TWA)
        # هاد الـ Action هو اللي غيحل لينا المشكل دقة وحدة
        uses: flayks/pwa-to-apk-action@v1.1.0
        with:
          manifest-url: 'https://chrsd-ca487.web.app/manifest.json'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-App-APK
          path: ./*.apk
